### ISSUE TITLE
Problem with integration

### ISSUE THREAD

**Issue by Gulahuset12** [CJNE/pythermiagenesis#1]
Hello,

Has added the installation files to the configuration and changed settings in the heatpump.

When I then have to download the integration, I get problems when the port number and other info have to be filled in.

Port number is correct. what more information should be filled in? whatever I tested appears required. What am I doing wrong?

![20220313_092703](https://user-images.githubusercontent.com/99580753/158051543-ec6e0509-4d21-43dd-9148-415278e3fd35.jpg)

**Comment by CJNE** [comment]
Oh the firm seems to be missing labels, the required field you're missing is the IP address of your heat pump.

**Comment by Gulahuset12** [comment]
I have tried with heatpump ip but it doesent work. 
 Think i need to check everything again 🙂

**Comment by Gulahuset12** [comment]
Now its working 👍  it was wrong Ip .

**Comment by CJNE** [comment]
Good to hear :)
